name: RandomTrip
main: randomtrip.io.github.yyyork.RandomTrip
version: 1.0
api-version: 1.16
commands:
  randomtrip:
    usage: "/randomtrip go"
    description: "just go!"
permissions:
  randomtrip.go:
    description: Allow a person sail
    default: false
  randomtrip.vipgo:
    description: Allow a vip person sail
    default: false